// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	getState: () => __TAURI_INVOKE<SimState>("get_state"),
};

/* Types */
export type SimState = {
	position: [number, number, number],
	attitude: [number, number, number, number],
	velocity: [number, number, number],
};

