// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	loadDemoFileAsIbd: (demoName: string) => typedError<IronbirdProject, CommandError>(__TAURI_INVOKE("load_demo_file_as_ibd", { demoName })),
};

/* Types */
/**
 *  Wrapper type for anyhow errors so they can be 
 *  sent across the wire for Tauri.
 */
export type CommandError = string;

export type Component = {
	id: string,
	ports: Ports,
} & (ComponentKind);

/**
 *  Exhaustive list of component types recognized
 *  in .ibd v1 files. To add a new component: add 
 *  a module here, define its Config (and initial 
 *  if stateful), then add a variant below.
 */
export type ComponentKind = { component_type: "pendulum"; config: PendulumConfig; initial: PendulumInitial } | { component_type: "pd_controller"; config: PdControllerConfig };

export type IronbirdProject = {
	schema_version: string,
	project_name: string,
	components: Component[],
	wiring: Wire[],
};

export type PdControllerConfig = {
	kp: number,
	kd: number,
	target_angle_rad: number,
};

export type PendulumConfig = {
	length_m: number,
	mass_kg: number,
	damping: number,
	gravity: number,
};

export type PendulumInitial = {
	angle_rad: number,
	angular_velocity_rad_s: number,
};

export type Ports = {
	inputs: string[],
	outputs: string[],
};

export type Wire = {
	from: string,
	from_port: string,
	to: string,
	to_port: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

